### ISSUE TITLE
Allow deleting a value from create alias modal

### ISSUE THREAD

**Issue by GuiLucena** [the-orange-team/orange-bot#28]
If a new value is added and it's not needed anymore the user isn't able to delete the field. 
![image](https://user-images.githubusercontent.com/8261910/119009114-31044480-b969-11eb-9488-97411750af38.png)

**Comment by romulogmp** [comment]
Fixed on https://github.com/the-orange-team/orange-bot/commit/0564c26cb1c0d157f75c52e8bcfea05d432c7b23.
