### ISSUE TITLE
Validate command creation to avoid unusable commands

### ISSUE THREAD

**Issue by GuiLucena** [the-orange-team/orange-bot#9]
Commands can be created using emojis or starting with colon, but those commands can't be executed since the regex will ignore those kinds of keywords.

![image](https://user-images.githubusercontent.com/8261910/116887044-3559ff00-ac00-11eb-8977-1e31f3fa2ba2.png)

**Comment by ThomazFB** [comment]
Fixed starting from e1f5d0f725444ec81009d1e017caf06e2851f0ca
